on:
jobs:
  scale_down_app:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Install EB CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip
        pip3 install --user awsebcli
        echo 'export PATH="$HOME/.local/bin:$PATH"' >> $GITHUB_ENV
    - name: Display PATH
      run: echo $PATH
    - name: test
      run: |
          cd docker
          chmod 755 -R .
          ./docker/test.sh
